# Curaçao
domains:
  - domain: gobiernu.cw
    organization: Government of Curaçao
    sector: Government
  - domain: government.cw
    organization: Government of Curaçao (English)
    sector: Government
  - domain: curacao.com
    organization: Curaçao Tourist Board
    sector: Government
  - domain: uts.cw
    organization: United Telecommunication Services (UTS)
    sector: Telecommunications
  - domain: digicelcuracao.com
    organization: Digicel Curaçao
    sector: Telecommunications
  - domain: flowcuracao.com
    organization: FLOW Curaçao
    sector: Telecommunications
  - domain: uoc.cw
    organization: University of Curaçao
    sector: Education
  - domain: una.cw
    organization: University of the Netherlands Antilles legacy / education
    sector: Education
  - domain: cbs.cw
    organization: Central Bureau of Statistics Curaçao
    sector: Government
  - domain: douane.cw
    organization: Customs Curaçao
    sector: Government
  - domain: centralbank.cw
    organization: Centrale Bank van Curaçao en Sint Maarten
    sector: Government
  - domain: btv.cw
    organization: Bureau Telecommunicatie en Post
    sector: Government
